extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier/react

plugins:
  - prettier

parser: babel-eslint

env:
  node: true
  jest: true
  browser: true

globals:
  fetch: false

rules:
  no-console: off
  indent:
    - error
    - 2
  space-before-function-paren:
    - error
    - never