language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: ./node_modules/.bin/eslint src/*.js
    - stage: test
      script: npm test